### ISSUE TITLE
Please remove your app from Fdroid market and learn good manners before you attach yourselves to the Templars. Reason being you don't invite to install in order to deny due to invitation of some sort. Remove it. 

### ISSUE THREAD

**Issue by TohellwithCtemplar** [CTemplar/android#148]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung S8/iPhone6]
 - OS: [e.g. Android 6/ iOS8.1]

**Additional context**

**Comment by Godfry** [comment]
Hello @TohellwithCtemplar 

Thank you for your comment.  I am the owner of CTemplar and respectfully decline your request.  

We have closed new account creation on F-Droid because someone created thousands of free accounts on F-Droid and used them to bulk/spam sextortion emails.  This user violated our terms of service by sending bulk/spam emails.  We are in the process of implementing invite codes on F-Droid so this user cannot create thousands of accounts and send bulk/spam emails. Until that time we will keep our app on the F-Droid market to support our existing users.  

Kind Regards,
Godfrey de Saint Omer
CTemplar Founder
