### ISSUE TITLE
Cannot set different language after auto-detect has been enabled by the application

### ISSUE THREAD

**Issue by vxern** [CTemplar/android#310]
Steps to reproduce:

1. Set language of device to language that is not yet supported by CTemplar [Romanian]
2. Set app language to English
3. Set device to Russian
4. Attempt to switch app to English from auto-detected Russian

**Comment by alexdwork2018** [comment]
Hi @vxern !

The manually selected language overrides the one automatically detected by the system, so the script you described should work fine. Please write your Android version and device model so that I can check the problem in more detail.

Also I have some additional questions. What language is displayed in the settings after restarting the app? Does manual language selection work on your device under normal conditions?

**Comment by The-Hidden-Hand** [comment]
Dear @vxern 
Are you able to provide feedback?

**Comment by vxern** [comment]
I apologise for the lack of response @The-Hidden-Hand @alexdwork2018 . After restarting the app, I still saw Russian as the language, even after setting the language to English.

What do you mean by 'under normal conditions'?

**Comment by alexdwork2018** [comment]
Hello @vxern

After selecting the language in the app settings, you need to close and reopen the app. The app will be opened with the selected in the app settings language. When Auto (Detect) language is selected, the app will display the language in accordance with the Android system language, and in the absence of support for this language by the app - English.
Does what I described work for your device? If not, then please let us know your device model, Android version, as well as the version of the app with which you are experiencing the problem.
