### ISSUE TITLE
Three UI/UX improvements from a customer

### ISSUE THREAD

**Issue by The-Hidden-Hand** [CTemplar/android#337]
### Expected behavior

- [ ] After deleting any message or saving them in the drafts, when I click on the 3 line bar that shows all the folders, there is no numbering besides the folders (Drafts, Trash etc.) to show how many messages are in it. This should be fixed.

- [ ] After tapping on the send icon, the "Sending" appears on the middle of the screen. It should be on the bottom of the screen, and the user can do other things on the email app, even if the user exists the app, the "Mail Sent" notification should appear after the mail is sent.

- [ ] In the All Mails or in the Inbox, the subject lines should be in large and bold fonts and the mail's body in normal fonts.

**Comment by alexdwork2018** [comment]
@The-Hidden-Hand hi
1. On the screenshot you can see, that number of unread drafts is displayed correctly. I made preparatory procedures for more flexible work with custom folders and unread counters. So I can add unread counters for all folders, but you need to implement this on the backend also.
2. This is a standard Android toast message. Usually, it is displayed at the very bottom of the screen. But it may variate related to device vendor. I think I can make a custom alert or display info as a notification. I'll think about what's better.
3. The message layout title is already bold. But it is bold only when a message is unread. When the user has read the message font changes to the regular one. Do I need to always use a bold font on the message item subject?

**Comment by alexdwork2018** [comment]
@The-Hidden-Hand I checked point 2 again. Probably the customer means the progress bar with the message, not the toast pop-up message. This progress bar displays until the app gets the public keys for the email recipients (the step before sending a message). I can move the logic of getting the public keys of the recipients to the Sending Service (which does main processing for mail sending after closing the compose screen) and remove the progress bar. This will allow closing the compose email screen immediately after click on the send mail button. But if the user faces any issue with receiving recipients' public keys (for example connection issues..), mail will not be sent and will be lost. I can save it as a draft before sending it to prevent it.
Web Client also displays a 'processing' message on the sending button. But I don't know what it exactly doing in the background.
What do you think would be the best option?
![](https://user-images.githubusercontent.com/44965210/153930283-983c510b-fa1d-42fa-8fea-d7eacb5f4e42.png)
![](https://user-images.githubusercontent.com/44965210/153930454-a4eb28b9-98dc-4279-9a25-d8fedcd9b5a0.png)

**Comment by The-Hidden-Hand** [comment]
> So I can add unread counters for all folders, but you need to implement this on the backend also.

Can you see if that's working on the webclient? I think backend sends that data using websockets.

> The message layout title is already bold. But it is bold only when a message is unread. When the user has read the message font changes to the regular one. Do I need to always use a bold font on the message item subject?

I know it goes against the original design. On the webclient it was like that but I asked to change from gray background for read messages to the opposite, so the state of all white background means everything is read. Would that help?

---

>  I can move the logic of getting the public keys of the recipients to the Sending Service (which does main processing for mail sending after closing the compose screen) and remove the progress bar. This will allow closing the compose email screen immediately after click on the send mail button.

That may improve performance feeling.

> But if the user faces any issue with receiving recipients' public keys (for example connection issues..), mail will not be sent and will be lost. I can save it as a draft before sending it to prevent it.

Consider saving it only in case it fails, if can still preventing data loss and it gives performance feeling.


@alexdwork2018

**Comment by alexdwork2018** [comment]
> Can you see if that's working on the webclient? I think backend sends that data using websockets.

OK. Now Web Sockets are implemented only in the F-Droid versions of the app. It used in a separate Notification Service. But a separate foreground service has a bad effect on the battery and is not needed in Google Play version which uses Firebase Notifications. Because of this for the Google Play version I will implement Web Sockets only for real-time unread counters update.
FYI. Except real-time update unread counter display works the same way as on the Web Client. Now the Android client displays the number of unread folders for: Inbox, Draft, Outbox, Starred, Spam, Unread and for all custom folders.

> I know it goes against the original design. On the webclient it was like that but I asked to change from gray background for read messages to the opposite, so the state of all white background means everything is read. Would that help?

In the Android app, unread messages have a bold font (subject) and a gray background. Read messages have a regular font and an almost white background. Thus, the Android design already complies with the Web Client version.
What do i need to change? (screenshots attached).
<img src="https://user-images.githubusercontent.com/44965210/155796024-f7d2bfa2-0342-49eb-a7df-09d7977f4b8b.png" />
<img src="https://user-images.githubusercontent.com/44965210/155796055-880a6b60-703b-46d5-912c-c5142cb05520.png" width="400px" /><img src="https://user-images.githubusercontent.com/44965210/155796081-f13de6b1-20b1-4543-8952-be6a2b159d64.png" width="400px" />

**Comment by alexdwork2018** [comment]
> Can you see if that's working on the webclient? I think backend sends that data using websockets.

OK. Now Web Sockets are implemented only in the F-Droid versions of the app. It used in a separate Notification Service. But a separate foreground service has a bad effect on the battery and is not needed in Google Play version which uses Firebase Notifications. Because of this for the Google Play version I will implement Web Sockets only for real-time unread counters update.
FYI. Except real-time update, unread counter display works the same way as on the Web Client. Now the Android client displays the number of unread folders for: Inbox, Draft, Outbox, Starred, Spam, Unread and for all custom folders.

> I know it goes against the original design. On the webclient it was like that but I asked to change from gray background for read messages to the opposite, so the state of all white background means everything is read. Would that help?

In the Android app, unread messages have a bold font (subject) and a gray background. Read messages have a regular font and an almost white background. Thus, the Android design already complies with the Web Client version.
What do i need to change? (screenshots attached)
<img src="https://user-images.githubusercontent.com/44965210/155796024-f7d2bfa2-0342-49eb-a7df-09d7977f4b8b.png" />
<img src="https://user-images.githubusercontent.com/44965210/155796055-880a6b60-703b-46d5-912c-c5142cb05520.png" width="400px" /><img src="https://user-images.githubusercontent.com/44965210/155796081-f13de6b1-20b1-4543-8952-be6a2b159d64.png" width="400px" />

**Comment by The-Hidden-Hand** [comment]
@alexdwork2018 Ok, got it. Nothing to change for the unread unless you want to invert the color (gray <> white).

**Comment by alexdwork2018** [comment]
@The-Hidden-Hand Okay, no problem, I'll swap the colors of read and unread messages. Then everything will be exactly as it is now on the WebClient.

You closed this ticket, but I currently finalizing the real-time unread folder counters (subtask 1)... Next, I planned to work on improving sending messages flow (subtask 2). Should I continue with subtask 2?

**Comment by alexdwork2018** [comment]
@The-Hidden-Hand Also about subtask 1. Real-time update unread folder counters already works. Old code for work with custom folders and its counters was also optimized. But for now, counters update only on receiving a new email. The backend doesn't send socket messages about unread folders on delete/create draft actions. So, described by the user scenario still not working.

**Comment by The-Hidden-Hand** [comment]
Right, the webclient manages some states on memory, such as the read / unread status.
