### ISSUE TITLE
Make the app work smoother

### ISSUE THREAD

**Issue by The-Hidden-Hand** [CTemplar/android#397]
### Expected behavior

The app works smoothly on most devices.

### Actual behavior

Certain users complain about the app having lag, being difficult to work with it intensely, and even sending emails from the wrong alias because of that. I know this will vary from device to device, but perhaps there is something obvious / structural that will make a noticeable improvement, at least for the basic navigation and actions.

**Comment by alexdwork2018** [comment]
Most of the latency is due to the decryption library. When the user logs in for the first time and opens folders, it initiates decryption of all displayed subjects in each folder which he opens. Further, these subjects are displayed from the local DB. Users can disable local subjects caching if it is worried about data safety but they can't disable on-fly subjects decrypting itself. Each message opening also initiates decryption of the message content, which doesn't store in decrypted form event in the local DB due to security purposes.

You wrote that some users mistakenly sent emails from the wrong alias. Can you describe this bug in more detail? Is it due to the interface freezing or for some other reason? If yes, have they experienced performance issues before opens compose screen? Perhaps they open multiple emails in a short period of time which can be a reason for an intensive load on the old user devices.

**Comment by The-Hidden-Hand** [comment]
@alexdwork2018 
Is there any middle point you can envision? Perhaps canceling or stopping the decryption right after it goes in the background.

So you decrypt while "on sight" but stop when not, so hopefully the actions don't build up and there is always a single process (?).

**Comment by alexdwork2018** [comment]
@The-Hidden-Hand Yes, decryption always uses one executor process and is also cleared when the user reopen the app
